### ISSUE TITLE
Trustworthy - Reliable - to be or not to be?

### ISSUE THREAD

**Issue by TomFreudenberg** [chartshq/muze#286]
Hey out there from @chartshq-eng 

First of all - thanks for opening this cool tool and library for free usage to all! That is great stuff.

But let's move on to concerns ...

In times where are a lot of trojans, viruses and others are out in the wild - it is very important to be "trustworthy" - especially when developing software for customers and deploying that to a number of clients. For that kind IMHO there is nothing else than "Open Source" (see what you get).

Now I ask myself how to thrust a WebAssembly which is not allowed to get reverse engineerd by license but free to use. How to trust that piece of "closed" code.

I am looking forward to your answer - how to solve that.

Cheers,
Tom

**Comment by UD-UD** [comment]
Unfortunately we cannot open the code because of some licensing issue yet. However, like with other executables, you can run any security review on top of it to detect any such security issues.
That being said, we have many users who are using the library, and while that doesn’t directly answer the issues of security, but that’s a proof that it’s intended to just do visualisations and nothing else.

**Comment by TomFreudenberg** [comment]
Hey @UD-UD 

thanks for the feedback - even it does not answer the question at all.

"many users who are using the library" is at least not a trustworthy statement.

You may have heard that e.g. the european and us intelligence agencies had deployed a special and manipulated calculator to catch communication of international criminals. Therefor I am sure that there are a number of tools outside in the wild prepared and ready to inject some unintended features. 

That's nothing you may have in mind (currently) but at least - without code and the option to build yourself - no trust.

I am pretty sure that you can understand that feeling.

Cheers
Tom

**Comment by UD-UD** [comment]
@TomFreudenberg 
Thanks for your feedback. I believe having trust on a particular tools comes after rigorous usage and testing. And users of our product are free to run any required security analysis if they have any concerns.

You can always fall back to our JavaScript Version  [Muze v1.3.2](https://github.com/chartshq/muze-deprecated) whose code is open sourced but the performance will not be as good as the latter.

Having said that please reach out to us eng@charts.com if you want to integrate Muze in your product and then based on your project we can work something up so that you can have code access. But for now due to some pending action items , we will not be able to open the code to public.

Thanks,
Ujjal
