### ISSUE TITLE
Uncaught TypeError: v is not a function on bar hover without any tooltip config

### ISSUE THREAD

**Issue by swapsCAPS** [chartshq/muze#40]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Console.errors with `Uncaught TypeError: v is not a function` when you hover over a bar in a bar chart without any tooltip config.

**What is the expected behavior?**
No errors

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
1.0.3 Chrome

**Comment by ranajitbanerjee** [comment]
@swapsCAPS  Cannot replicate the issue. Can you please share the data and the code sample?

**Comment by adotg** [comment]
@ranajitbanerjee 
Replicated
https://jsfiddle.net/a72zypv1/3/

**Comment by ranajitbanerjee** [comment]
@swapsCAPS Working version https://jsfiddle.net/a72zypv1/8/. the variable `day` is just a categorical variable, not a temporal variable in this context. And there is no subtype called  'datetime'. Did you see anywhere in docs that the subtype of a variable is written as 'datetime' ?

However, the expected behaviour is to ignore this `datetime` subtype and treat it as `categorical`. Which i am gonna fix.

**Comment by swapsCAPS** [comment]
No did not see it in the docs. In the source I think, yesterday at the end of the day when I was fiddling around trying to fix it.

**Comment by adotg** [comment]
Reopening this as 
> ignore `datetime` subtype and treat it as `categorical`

needs to be fixed.
