### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by aarthi0808** [chartshq/muze#43]
**Under cross interaction docs, you have mentioned that attached some illustration. But there is no such illustration and proper demo. Please attach proper demos and explanation for cross connected charts simply using data model**

**Also API for Muze is missing. So unable to understand **ActionModel,sideEffects****

**Comment by adotg** [comment]
@aarthi0808 

Interaction documents are incomplete. Since interaction includes some concepts and heavily uses Muze's API we want to make sure its comprehensible to everyone. We will be pushing the progress in about 10 days.

We have created two basic interaction sample to highlight two different concepts of interaction. Please have a look.
https://jsfiddle.net/p7bqo4kf/10/
https://jsfiddle.net/exm1trfk/23/

You can find more interaction samples in the following list
https://www.charts.com/muze/examples/view/concurrent-tooltip
https://www.charts.com/muze/examples/view/crossfiltering-with-dynamic-layer-addition
