### ISSUE TITLE
Updating chart config with different rows does not update domain

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#80]
**Do you want to request a *feature* or report a *bug*?**
* Bug

**What is the current behavior?**
After plotting a dimension vs a measure, if I update the measure to use a different field the domain of the previous measure is used by the axis.
See the attached screen shots below.

Supplying Revenue field in colums array `.columns(['Revenue'])`
![image](https://user-images.githubusercontent.com/7683718/50963436-b7373300-14f2-11e9-8243-a2938be0db33.png)

After updating the canvas to use expense field `.columns(['Expense'])` the domain of Revenue is used
even though the max value Expense much smaller.
![image](https://user-images.githubusercontent.com/7683718/50963474-cf0eb700-14f2-11e9-991c-00456f8f26f9.png)

**What is the expected behavior?**
When rows or columns config is updated the domain of the axis should also change.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* Latest version

**Comment by UD-UD** [comment]
Working as expected in develop branch.
Issue is fixed in develop.:
Please refer below screenshots:
When `.columns(['Cylinders'])`
![image](https://user-images.githubusercontent.com/16508993/51312652-c9c0e780-1a71-11e9-9c5b-2d2c48d91bce.png)

When it is updated to `.columns(['Origin'])`
![image](https://user-images.githubusercontent.com/16508993/51312756-042a8480-1a72-11e9-9581-e8a5bbbbf31a.png)

When rows updated as `.rows(['CountVehicle'])`
![image](https://user-images.githubusercontent.com/16508993/51312841-3805aa00-1a72-11e9-9e1b-b8b9d8c1fff8.png)
