### ISSUE TITLE
Inappropriate legend alignment and spacing between legend and axis labels

### ISSUE THREAD

**Issue by sanjaymahto** [chartshq/muze#99]
**bug**

1.) Legend alignment is not correct, it should be according to centre matrix.
2.) spacing between the legend title and X-axis label is incorrect.

**What is the current behaviour?**
1.) when the legend is Positioned top or bottom, the legend is aligned according to the root container (topmost parent container of muze).
2.) The spacing between the legend Title and X-axis label is not correct. 

**code**
```
    canvas
    .data(dm)
    .width(600)
    .height(400)
    .rows(['Displacement'])
    .columns(['Horsepower'])
    .color('Origin')
    .detail(['Name'])
    .config({
        legend: {
            position: 'bottom'
        }
    })
    .mount(node) /* Attaching the canvas to DOM element */
```

https://user-images.githubusercontent.com/25404832/51259746-c9bdda80-19d2-11e9-93cc-6c7edba0a9b0.png

**What is the expected behaviour?**
1.) when legend should be positioned bottom or top, it should be aligned according to the centre matrix.
2.) spacing between the legend title and X-axis label should be 2 times the spacing between the axis and axis labels.

**Comment by UD-UD** [comment]
Resolved.

PFA below screenshots:

**BOTTOM**
<img width="950" alt="screenshot 2019-01-25 at 4 19 45 pm" src="https://user-images.githubusercontent.com/16508993/51741586-62341900-20bd-11e9-8e18-a30ba1226591.png">

**BOTTOM GRADIENT NO AXIS LABLE**
<img width="915" alt="screenshot 2019-01-25 at 4 17 43 pm" src="https://user-images.githubusercontent.com/16508993/51741608-6d874480-20bd-11e9-9d39-71aada60fd27.png">

**GRADIENT TOP**
<img width="938" alt="screenshot 2019-01-25 at 4 18 16 pm" src="https://user-images.githubusercontent.com/16508993/51741593-67916380-20bd-11e9-9aa6-5af911bb1016.png">

**RIGHT**
<img width="891" alt="screenshot 2019-01-25 at 4 24 18 pm" src="https://user-images.githubusercontent.com/16508993/51741717-ba6b1b00-20bd-11e9-8068-49079df24631.png">

Note : When subtitle is used, Visual matrices uses less space then available.
This issue is tracked under 
#114
